export default interface RecipeData {
  id: string,
  photo: string,
  title: string,
  course: string[],
  cuisine: string[],
  servings: number,
  calories: number,
  ingredientList: {
    ingredient: string,
    quantity: string,
  }[],
  instructions: string,
  keywords: string[],
  glutenFree: boolean,
  vegan: boolean,
  vegetarian: boolean,
  nutFree: boolean,
  dairyFree: boolean,
  vegatableFoodGroup: boolean,
  dairyFoodGroup: boolean,
  grainFoodGroup: boolean,
  fruitFoodGroup: boolean,
  proteinFoodGroup: boolean,
  videoLink: string,
}
